backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    fields:
      - { name: Title }

  - name: "nav"
    label: "Nav"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/nav.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: Name, name: text, widget: string }
              - { label: Link, name: link, widget: string }

  - name: "logo"
    label: "Logo"
    editor:
      preview: false
    files:
      - label: "Logo"
        name: "loo"
        file: "_data/nav.yml"
        fields:
          - label: "Logo"
            name: "logoitem"
            widget: "list"
            fields:
              - { label: Name, name: logourl, widget: image }
              - { label: Link, name: logoalt, widget: string }

  - name: "hero"
    label: "Hero"
    editor:
      preview: false
    files:
      - label: "Hero"
        name: "hero"
        file: "_data/hero.yml"
        fields:
          - label: "Hero text"
            name: "items"
            widget: "list"
            fields:
              - { label: Hero, name: hero, widget: string }
              - { label: Intro, name: intro, widget: string }
              - { label: Download, name: resume, widget: string }
              - { label: Link, name: resumelink, widget: string }
